# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe4d4309d341aba9f7c15731654c79f41f4ac39561645999ec0b8bc2b710356d7aa5d8dd1285a6bda0d12187d5a8354087e160a442e02fe33e235570aa11640

test:
  secret_key_base: b5946e4d697ff8ad060eb0fdbabdd6c8d2bd8150cb8eaacd6b0743620d667687b0b62c9a62b374d101c23705152e53d138fb0b387d881db4d4f4cd011501af39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
